name: Authorize Commit Signing

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  verify-signature-with-Beyond-Identity:
    runs-on: ubuntu-latest
    steps:
      - name: Check out pull request
        uses: actions/checkout@v2
        with:
          # Critical: check out the head commit on the branch. By default,
          # actions/checkout will check out a merge commit built for the pull
          # request and signed by Github itself. Using the pull-request HEAD
          # allows the action to check the latest commit on the pull request,
          # which must be signed by an authorized user before it can be merged.
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Authorize with Beyond Identity
        uses: byndid/auth-commit-sig@v0
        with:
          api_token: ${{ secrets.API_TOKEN }}
          
  byndid-auth-commit-sig-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out pull request
        uses: actions/checkout@v2
        with:
          # Critical: check out the head commit on the branch. By default,
          # actions/checkout will check out a merge commit built for the pull
          # request and signed by Github itself. Using the pull-request HEAD
          # allows the action to check the latest commit on the pull request,
          # which must be signed by an authorized user before it can be merged.
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Authorize with Beyond Identity
        # Specifying @main here so that we always test against the latest, even
        # if that's a release candidate.
        uses: byndid/auth-commit-sig@main
        with:
          api_token: ${{ secrets.API_TOKEN }}

